"""add lat and lon field in jobs table

Revision ID: 506835237d46
Revises: 27bbedbb1d05
Create Date: 2025-06-15 15:05:02.568131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506835237d46'
down_revision = '27bbedbb1d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('address_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('lat', sa.Float(), nullable=True, comment='Latitude in decimal degrees'))
    op.add_column('jobs', sa.Column('lon', sa.Float(), nullable=True, comment='Longitude in decimal degrees'))
    op.create_index(op.f('ix_jobs_lat'), 'jobs', ['lat'], unique=False)
    op.create_index(op.f('ix_jobs_lon'), 'jobs', ['lon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_lon'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_lat'), table_name='jobs')
    op.drop_column('jobs', 'lon')
    op.drop_column('jobs', 'lat')
    op.drop_column('jobs', 'address_id')
    # ### end Alembic commands ###
