"""Create job table

Revision ID: d563a53ac1cc
Revises: 
Create Date: 2025-06-04 23:36:04.673930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd563a53ac1cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('documents', sa.JSON(), nullable=True, comment='Array of file paths/urls'))
    op.drop_column('jobs', 'document_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('document_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Array of file paths/urls'))
    op.drop_column('jobs', 'documents')
    # ### end Alembic commands ###
