"""update jobs nullable fields

Revision ID: feb79353db35
Revises: beed49420ecd
Create Date: 2025-06-09 21:53:18.206687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'feb79353db35'
down_revision = 'beed49420ecd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Array of file metadata with paths and info',
               existing_comment='Array of file paths/urls',
               existing_nullable=True)
    op.alter_column('jobs', 'payment_status',
               existing_type=postgresql.ENUM('paid', 'unpaid', name='paymentstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'payment_status',
               existing_type=postgresql.ENUM('paid', 'unpaid', name='paymentstatus'),
               nullable=True)
    op.alter_column('jobs', 'documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Array of file paths/urls',
               existing_comment='Array of file metadata with paths and info',
               existing_nullable=True)
    op.alter_column('jobs', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
